# Generated by Django 4.2.29 on 2026-04-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='first_name',
            field=models.CharField(default=' ', max_length=150),
        ),
        migrations.AddField(
            model_name='author',
            name='last_name',
            field=models.CharField(default=' ', max_length=150),
        ),
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.CharField(blank=True, default=' ', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image_name',
            field=models.CharField(default=' ', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=' ', max_length=150),
        ),
        migrations.AddField(
            model_name='tag',
            name='caption',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
